##  Combine & Split an Array

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### np.concatenate((a, b), axis=0)

In [3]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [5]:
# concat along the row
var = np.concatenate((arr1, arr2), axis=1)        
print(var)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [6]:
var = np.concatenate((arr1, arr2), axis=0)        
print(var)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


##### Stacking: np.hstack() and n.vstack()
Stacking is done using the np.hstack() and np.vstack() methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same

In [7]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [8]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


#### np.hstack((a, b))
#### np.c_[a, b]

In [9]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [10]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array

In [11]:
arr = np.random.rand(6,6)

In [12]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.43067086, 0.18350019, 0.04572316, 0.28859037, 0.58379952,
        0.40173694],
       [0.32598131, 0.4222612 , 0.16164641, 0.06659883, 0.06869372,
        0.01178626],
       [0.74235799, 0.80945154, 0.47465227, 0.76440984, 0.53403878,
        0.92477211]]), array([[0.28057761, 0.67117552, 0.79138938, 0.11590671, 0.36590313,
        0.11777084],
       [0.63507842, 0.54770237, 0.84461002, 0.17446167, 0.72195411,
        0.74032883],
       [0.98738879, 0.2915008 , 0.42680535, 0.34520911, 0.29157001,
        0.73830483]])]


In [13]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.43067086, 0.18350019, 0.04572316],
       [0.32598131, 0.4222612 , 0.16164641],
       [0.74235799, 0.80945154, 0.47465227],
       [0.28057761, 0.67117552, 0.79138938],
       [0.63507842, 0.54770237, 0.84461002],
       [0.98738879, 0.2915008 , 0.42680535]]), array([[0.28859037, 0.58379952, 0.40173694],
       [0.06659883, 0.06869372, 0.01178626],
       [0.76440984, 0.53403878, 0.92477211],
       [0.11590671, 0.36590313, 0.11777084],
       [0.17446167, 0.72195411, 0.74032883],
       [0.34520911, 0.29157001, 0.73830483]])]
