## Linear Algebra

In [1]:
import numpy as np 

In [2]:
arr1 = np.random.rand(3,3)
arr2 =np.random.rand(3,3)

### Matrix Manipulation 

In [3]:
print(arr1.dot(arr2))

[[0.76244631 0.2772252  1.31851297]
 [0.8750923  0.25808667 1.62465615]
 [0.51969502 0.14479401 1.04960276]]


###  OR

In [4]:
print(np.dot(arr1, arr2))

[[0.76244631 0.2772252  1.31851297]
 [0.8750923  0.25808667 1.62465615]
 [0.51969502 0.14479401 1.04960276]]


### OR

In [5]:
print(arr1 @ arr2)

[[0.76244631 0.2772252  1.31851297]
 [0.8750923  0.25808667 1.62465615]
 [0.51969502 0.14479401 1.04960276]]


### OR Factorization

In [6]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.63943457  0.33839903  0.15394527 -0.11448869 -0.66317623]
 [-0.14164611 -0.25944633  0.78596075  0.53478503  0.09431149]
 [-0.31996413 -0.65802319 -0.51534999  0.39123159 -0.21443104]
 [-0.35965923 -0.50296396  0.21895856 -0.70746653  0.26309836]
 [-0.58251867  0.36360203 -0.21222181  0.21754599  0.6603796 ]]
[[-1.35004023 -0.98745485 -0.77015147 -0.8516757  -1.37400062]
 [ 0.         -0.8178145  -0.18480623 -0.5292694  -0.68623609]
 [ 0.          0.          0.51380566  0.30780587  0.39248225]
 [ 0.          0.          0.          0.54002874  0.33190438]
 [ 0.          0.          0.          0.         -0.43650458]]


### singular value decomposition (SVD)

In [7]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.47204786 -0.08957546  0.22991423  0.83293341 -0.1500281 ]
 [-0.36085178  0.28936485  0.70787136 -0.28779678  0.44960553]
 [-0.55525265 -0.3605923   0.04290529 -0.47014084 -0.58206049]
 [-0.29642236  0.85203428 -0.35021501 -0.02486676 -0.25080365]
 [-0.50078448 -0.22859354 -0.56706805 -0.04176336  0.6112688 ]]
[2.52787887 0.97151933 0.83458575 0.21092729 0.12923248]
[[-0.38292994 -0.40832098 -0.5493482  -0.28761347 -0.54966688]
 [ 0.72461514 -0.06142574 -0.51453348  0.42284064 -0.16619527]
 [-0.28960636 -0.62684232 -0.11439148  0.4754998   0.53292719]
 [-0.32589807  0.17269358  0.27364288  0.70324809 -0.54270532]
 [-0.37177434  0.63776679 -0.58779759  0.13351533  0.30282833]]


### compute eigen values

In [8]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.07977404+0.j         -0.20572099+0.54769379j -0.20572099-0.54769379j
  0.52903864+0.j          0.35269044+0.j        ]


### eigen value decomposition

In [9]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.70061654+0.j          0.12339239+0.34946336j  0.12339239-0.34946336j
 -0.30694254+0.j          0.15764713+0.j        ]
[[ 0.33290813+0.j          0.40540657-0.43840899j  0.40540657+0.43840899j
   0.45419034+0.j          0.07502477+0.j        ]
 [ 0.41931637+0.j          0.01944696+0.18628099j  0.01944696-0.18628099j
  -0.35838926+0.j          0.64562957+0.j        ]
 [ 0.37597852+0.j         -0.69892059+0.j         -0.69892059-0.j
  -0.53523442+0.j         -0.14771502+0.j        ]
 [ 0.53239847+0.j          0.29321414+0.03269194j  0.29321414-0.03269194j
  -0.19545109+0.j         -0.72715098+0.j        ]
 [ 0.53715732+0.j         -0.18117029+0.0028856j  -0.18117029-0.0028856j
   0.58360198+0.j         -0.16421163+0.j        ]]


### compute the trace & determinant

In [10]:
# notice this is not a function in linalg!!!
print(np.trace(arr))  

2.7981059063575673


In [11]:
print(np.linalg.det(arr))

-0.017948812956348717


### calculate the inverse/psedo-inverse of a matrix

In [12]:
arr = np.random.rand(3,3)

In [13]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[ 0.29987423 -2.63760448  2.75814044]
 [-0.47608023  1.80172135 -0.36850776]
 [ 1.38005284  0.99602521 -1.77753521]]


In [14]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[ 0.29987423 -2.63760448  2.75814044]
 [-0.47608023  1.80172135 -0.36850776]
 [ 1.38005284  0.99602521 -1.77753521]]


### solve a linear system

In [15]:
# solve a linear system in closed form
y = [1,2,3]
print(np.linalg.solve(arr, y))

[ 3.2990866   2.02183919 -1.96050238]


In [16]:
# calculate the least-squares solution of a linear system
y = [1,2,3]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y,rcond=-1)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 3.2990866   2.02183919 -1.96050238]
[]
3
[1.46497275 0.57192566 0.21928568]
