## create Numpy Arrays with Random Numbers

In [1]:
import numpy as np

* rand() : the function isd used to generated a * ** random number value between the 0 & 1
* randn() : the function is used to generated a ranom number value closed to zero.
* This may return postive or negative numbers as well.
* ranf() : the function for diong random sampling in numpy. it returns an array of specified shape and filld it with random floats in the half evren interval [0.0,1.0].
* randint() : th e function is used to generated a random number given range

In [2]:
#generated a random scalar
print(np.random.rand())

0.8258986154621741


In [3]:
# generate a 1-D array
print(np.random.rand(3))

[0.57853631 0.45567188 0.47689121]


In [4]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.23248024 0.94072523 0.33963067]
 [0.29592478 0.33559057 0.19036722]
 [0.55562978 0.81301327 0.64499943]]


### Generate a sample from the standard normal distribution (mean = 0, var = 1)

In [5]:
print(np.random.randn(3,3))

[[ 0.07866081  0.36097849  1.08663642]
 [ 0.95923445 -0.4920248   0.73862751]
 [ 0.85478514  0.77562734  1.57937149]]


### Generate an array of random integers in a given interval [low, high)

In [6]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 8 8]


In [7]:
arr_randf = np.random.ranf(5)
print(arr_randf)

[0.80502086 0.95106621 0.07397779 0.98675854 0.56913758]


### Generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [8]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.14509753 0.11826173 0.53187049 0.37645718 0.37922647 0.12005331
 0.50877858 0.56227667 0.75719515 0.25863937]
[0.42062647 0.18226789 0.04540453 0.9198005  0.04576483 0.87325629
 0.43033989 0.41158777 0.83262339 0.77468263]
[0.1726169  0.5520271  0.14552345 0.8304705  0.81838425 0.31220928
 0.63159117 0.75101603 0.11656101 0.34734215]
[0.0623138  0.53702183 0.85754305 0.84915227 0.09695401 0.01321052
 0.16545589 0.56850772 0.35669128 0.21049508]


### Generate a random sample from a given 1-D array

In [9]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[0 2 1 1 1 1 1 1 1 1]


In [10]:
print(np.random.choice(3, 10))

[2 0 0 1 1 2 2 1 1 0]


In [11]:
print(np.random.choice([1,2,3], 10))

[2 2 2 3 2 2 2 2 3 3]


### Shuffle an array in place

In [12]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
np.random.shuffle(arr)
print(arr)

[3 1 8 5 6 7 2 4 0 9]


### Generate a permutation of an array

In [14]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [6 3 8 1 5 9 7 2 4 0]
