## NumPy Math Functions

In [1]:
import numpy as np 

In [2]:
arr = np.random.randint(10,99,[3,3])
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

### Element-wise addition, subtraction, multiplication and division

In [3]:
print("Addition:")
print(arr + 10)
print()
print("subtraction:")
print(arr - 10)
print()
print("multiplication:")
print(arr * 10)
print()
print("division:")
print(arr / 10)

Addition:
[[79 24 78]
 [24 42 32]
 [84 82 22]]

subtraction:
[[59  4 58]
 [ 4 22 12]
 [64 62  2]]

multiplication:
[[690 140 680]
 [140 320 220]
 [740 720 120]]

division:
[[6.9 1.4 6.8]
 [1.4 3.2 2.2]
 [7.4 7.2 1.2]]


In [4]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### Element-wise exponentiation

In [5]:
print(np.exp(arr))

[[9.25378173e+29 1.20260428e+06 3.40427605e+29]
 [1.20260428e+06 7.89629602e+13 3.58491285e+09]
 [1.37338298e+32 1.85867175e+31 1.62754791e+05]]


### Element-wise logorithm

In [6]:
# natural log
print(np.log(arr))      

[[4.2341065  2.63905733 4.21950771]
 [2.63905733 3.4657359  3.09104245]
 [4.30406509 4.27666612 2.48490665]]


In [7]:
# base 2
print(np.log2(arr)) 

[[6.10852446 3.80735492 6.08746284]
 [3.80735492 5.         4.45943162]
 [6.20945337 6.169925   3.5849625 ]]


In [8]:
# base 10
print(np.log10(arr))

[[1.83884909 1.14612804 1.83250891]
 [1.14612804 1.50514998 1.34242268]
 [1.86923172 1.8573325  1.07918125]]


### Element-wise square root

In [9]:
print(np.sqrt(arr))

[[8.30662386 3.74165739 8.24621125]
 [3.74165739 5.65685425 4.69041576]
 [8.60232527 8.48528137 3.46410162]]


### Element-wise sine and cosine

In [10]:
print(np.sin(arr))

[[-0.11478481  0.99060736 -0.89792768]
 [ 0.99060736  0.55142668 -0.00885131]
 [-0.98514626  0.25382336 -0.53657292]]


In [11]:
print(np.sin(arr))

[[-0.11478481  0.99060736 -0.89792768]
 [ 0.99060736  0.55142668 -0.00885131]
 [-0.98514626  0.25382336 -0.53657292]]


### Sum along a specified axis

In [12]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [13]:
# sum along the row
print(np.sum(arr, axis=0))

[157 118 102]


In [14]:
# sum along the column
print(np.sum(arr, axis=1)) 

[151  68 158]


### Compute the min and max along a specified axis

In [15]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [16]:
# calculate min along the row
print(np.min(arr, axis=0))

[14 14 12]


In [17]:
# calculate max along the column
print(np.max(arr, axis=1)) 

[69 32 74]


In [18]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

74
12


### Compute the indices of the min and max along a specified axis

In [19]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [20]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[1 0 2]
[2 2 0]


In [21]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 0 2]
[0 1 0]


In [22]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

8
6


### Compute element-wise min and max of two arrays

In [23]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### Split fractional and integral parts of a floating-point array

In [24]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.8456248  0.4305235  0.37524886 0.90883506 0.22210204 0.34491899
 0.44890445 0.52783797 0.5489963  0.26878722]
integral:  [5. 8. 8. 3. 7. 6. 2. 9. 1. 5.]


### Compute the mean

In [25]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [26]:
# compute the overall mean
print(np.mean(arr))

41.888888888888886


In [27]:
# compute the mean along the row
print(np.mean(arr, axis=0)) 

[52.33333333 39.33333333 34.        ]


In [28]:
# compute the mean along the column
print(np.mean(arr, axis=1))

[50.33333333 22.66666667 52.66666667]


### Compute the median

In [29]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [30]:
# compute the overall median
print(np.median(arr))


32.0


In [31]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[69. 32. 22.]


In [32]:
# compute the median along the column
print(np.median(arr, axis=1))

[68. 22. 72.]


### Compute the percentile

In [33]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.05227606 0.64279742 0.9579327 ]


### Compute the standard deviation & variance


In [34]:
arr

array([[69, 14, 68],
       [14, 32, 22],
       [74, 72, 12]])

In [35]:
# compute the overall standard deviation
print(np.std(arr))

26.450979584651574


In [36]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))


[27.18251072 24.23954528 24.38578821]


In [37]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[25.69478979  7.36357401 28.76726535]


In [38]:
# compute the overall variance
print(np.var(arr))

699.6543209876543


In [39]:
# compute the variance along the row
print(np.var(arr, axis=0))

[738.88888889 587.55555556 594.66666667]


In [40]:
# compute the variance along the column
print(np.var(arr, axis=1))

[660.22222222  54.22222222 827.55555556]


### Compute the covariance & correlation

In [41]:
arr = np.random.rand(5,8)
arr

array([[0.85578197, 0.1912857 , 0.08258694, 0.21523796, 0.44194709,
        0.03848352, 0.45207058, 0.09666096],
       [0.20129621, 0.99163754, 0.39442284, 0.46765553, 0.16372937,
        0.28692836, 0.96598719, 0.73284705],
       [0.49410928, 0.33697901, 0.06493217, 0.02866009, 0.20984109,
        0.43511465, 0.27163863, 0.41319013],
       [0.18487542, 0.91187981, 0.81935397, 0.10587005, 0.1407547 ,
        0.17978236, 0.29727466, 0.63511701],
       [0.26072498, 0.79518426, 0.57867564, 0.58005327, 0.97232982,
        0.20186421, 0.54249293, 0.00715393]])

In [42]:
print(np.cov(arr))

[[ 0.07544191 -0.02308548  0.01457643 -0.0405498   0.00893206]
 [-0.02308548  0.10967652  0.00174031  0.06003123  0.00243001]
 [ 0.01457643  0.00174031  0.02932593 -0.00244123 -0.03096036]
 [-0.0405498   0.06003123 -0.00244123  0.10735782  0.00507994]
 [ 0.00893206  0.00243001 -0.03096036  0.00507994  0.10188498]]


In [43]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.94115537]
 [-0.94115537  1.        ]]


### Compute cumulative sum & product

In [44]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))

[[0.85578197 0.1912857  0.08258694 0.21523796 0.44194709 0.03848352
  0.45207058 0.09666096]
 [1.05707817 1.18292324 0.47700978 0.68289349 0.60567646 0.32541188
  1.41805777 0.82950801]
 [1.55118746 1.51990224 0.54194195 0.71155358 0.81551755 0.76052653
  1.68969641 1.24269813]
 [1.73606287 2.43178205 1.36129592 0.81742363 0.95627225 0.94030889
  1.98697107 1.87781515]
 [1.99678785 3.22696631 1.93997156 1.3974769  1.92860207 1.1421731
  2.52946399 1.88496908]]


In [45]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1)) 

[[0.85578197 1.04706766 1.1296546  1.34489256 1.78683965 1.82532318
  2.27739376 2.37405472]
 [0.20129621 1.19293375 1.58735659 2.05501212 2.21874149 2.50566984
  3.47165703 4.20450408]
 [0.49410928 0.83108829 0.89602046 0.92468054 1.13452163 1.56963628
  1.84127491 2.25446504]
 [0.18487542 1.09675523 1.9161092  2.02197925 2.16273395 2.34251632
  2.63979098 3.27490799]
 [0.26072498 1.05590923 1.63458487 2.21463814 3.18696796 3.38883217
  3.93132509 3.93847903]]


In [46]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))

[[8.55781965e-01 1.91285699e-01 8.25869396e-02 2.15237959e-01
  4.41947092e-01 3.84835237e-02 4.52070584e-01 9.66609576e-02]
 [1.72265665e-01 1.89686079e-01 3.25741753e-02 1.00657222e-01
  7.23597176e-02 1.10420142e-02 4.36694392e-01 7.08376977e-02]
 [8.51180641e-02 6.39202267e-02 2.11511175e-03 2.88484487e-03
  1.51840418e-02 4.80454211e-03 1.18623068e-01 2.92694372e-02]
 [1.57362377e-02 5.82875642e-02 1.73302521e-03 3.05418667e-04
  2.13722531e-03 8.63771929e-04 3.52636324e-02 1.85895175e-02]
 [4.10283019e-03 4.63493535e-02 1.00285947e-03 1.77159096e-04
  2.07808790e-03 1.74364635e-04 1.91302711e-02 1.32988183e-04]]


In [47]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[8.55781965e-01 1.63698851e-01 1.35193871e-02 2.90988529e-03
  1.28601534e-03 4.94904018e-05 2.23731549e-05 2.16261057e-06]
 [2.01296209e-01 1.99612877e-01 7.87318777e-02 3.68193982e-02
  6.02841676e-03 1.72972371e-03 1.67089094e-03 1.22450750e-03]
 [4.94109282e-01 1.66504456e-01 1.08114949e-02 3.09858399e-04
  6.50210231e-05 2.82915995e-05 7.68509145e-06 3.17540390e-06]
 [1.84875418e-01 1.68584161e-01 1.38130102e-01 1.46238406e-02
  2.05837436e-03 3.70059404e-04 1.10009284e-04 6.98687678e-05]
 [2.60724976e-01 2.07324397e-01 1.19973577e-01 6.95910657e-02
  6.76654684e-02 1.36592361e-02 7.41003896e-03 5.30109303e-05]]


### Element-wise comparison

In [48]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [49]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)


[False False  True False False]
[ True  True False False False]
