## Sorting of an Array 

In [2]:
import numpy as np

In [7]:
arr = np.array([[30,17,15],[19,90,16],[69,53,21]]) 
arr

array([[30, 17, 15],
       [19, 90, 16],
       [69, 53, 21]])

### sort an array along a specified axis

In [8]:
# sort along the row and return a copy
print(np.sort(arr, axis=0)) 

[[19 17 15]
 [30 53 16]
 [69 90 21]]


In [9]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[19 17 15]
 [30 53 16]
 [69 90 21]]


In [10]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))

[[15 17 19]
 [16 30 53]
 [21 69 90]]


In [11]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[15 17 19]
 [16 30 53]
 [21 69 90]]


### Order parameter in sort function

In [12]:
dt = np.dtype([('name', 'S10'),('age', int)]) 
arr = np.array([("Karan",21),("Arpit",25),("Ashish", 17), ("Sam",27),("Robin",22)], dtype = dt)  
arr 

array([(b'Karan', 21), (b'Arpit', 25), (b'Ashish', 17), (b'Sam', 27),
       (b'Robin', 22)], dtype=[('name', 'S10'), ('age', '<i4')])

### Order by name¶

In [13]:
np.sort(arr, order = 'name')

array([(b'Arpit', 25), (b'Ashish', 17), (b'Karan', 21), (b'Robin', 22),
       (b'Sam', 27)], dtype=[('name', 'S10'), ('age', '<i4')])

### Order by age:

In [14]:
np.sort(arr, order = 'age')

array([(b'Ashish', 17), (b'Karan', 21), (b'Robin', 22), (b'Arpit', 25),
       (b'Sam', 27)], dtype=[('name', 'S10'), ('age', '<i4')])

### compute the indices that would sort an array along a specified axis

In [15]:
arr = np.random.rand(5,5)
arr

array([[0.48897492, 0.73496804, 0.7465687 , 0.99914293, 0.4057804 ],
       [0.47368446, 0.32344592, 0.90002478, 0.02302244, 0.30789063],
       [0.08311323, 0.43288063, 0.40523945, 0.61781306, 0.71226529],
       [0.31922786, 0.46233236, 0.64810468, 0.73288642, 0.74328919],
       [0.91232515, 0.36832296, 0.27462851, 0.38936916, 0.74795193]])

In [16]:
# along the row
print(np.argsort(arr, axis=0))

[[2 1 4 1 1]
 [3 4 2 4 0]
 [1 2 3 2 2]
 [0 3 0 3 3]
 [4 0 1 0 4]]


In [17]:
# along the column
print(np.argsort(arr, axis=1))

[[4 0 1 2 3]
 [3 4 1 0 2]
 [0 2 1 3 4]
 [0 1 2 3 4]
 [2 1 3 4 0]]


In [18]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 8 10 22  9 15  6 21 23 12  4 11 16  5  0 13 17 14 18  1 19  2 24  7 20
  3]
